import pandas as pd

# Add the comments you want to further amend into the csv file ...
new_comments = [
    "The professor's lectures were incredibly disorganized and hard to follow. They often seemed unprepared and lacked a clear structure. The course content was equally terrible, with outdated materials and assignments that seemed to have no real purpose. I found myself struggling to understand the basic concepts due to the poor quality of both the lectures and the course materials.",
    "This was by far the worst course I have ever taken. The professor was not only unengaging but also seemed completely uninterested in teaching. Their explanations were often confusing and lacked depth. The course itself was a nightmare, with poorly structured content and irrelevant assignments that did nothing to enhance my understanding of the subject.",
    "The professor was completely unapproachable and seemed to have no interest in helping students. Their lectures were rambling and incoherent, making it difficult to grasp even the simplest concepts. The course content was a mess, with disorganized materials and assignments that were neither challenging nor educational.",
    "I have never experienced such a poorly taught course in my academic career. The professor's lectures were confusing and lacked any logical flow. They often seemed to be reading from notes without understanding the material themselves. The course content was outdated and irrelevant, with assignments that seemed to be thrown together at the last minute.",
    "The professor was not only incompetent but also rude and dismissive of students' questions. Their lectures were painfully boring and uninformative. The course itself was a disaster, with materials that were outdated and assignments that made no sense. I learned more from Google than from the professor or the course materials.",
    "The professor's lack of enthusiasm and preparation was evident in every lecture. They often seemed to be making things up as they went along. The course content was equally terrible, with outdated materials and assignments that were either too easy or completely irrelevant. This course was a waste of time and money.",
    "The professor was one of the worst I have ever encountered. Their lectures were monotonous and unhelpful, and they rarely engaged with the students. The course content was equally disappointing, with poorly organized materials and assignments that did not contribute to my understanding of the subject. I would not recommend this course to anyone.",
    "The professor was consistently late to class and seemed to have no interest in teaching. Their lectures were disjointed and confusing, making it difficult to follow along. The course content was a joke, with outdated materials and assignments that seemed to have no real purpose. This was a terrible learning experience.",
    "The professor's lectures were poorly delivered and lacked any real substance. They often went off on tangents and failed to cover the necessary material. The course content was equally bad, with outdated readings and assignments that did not enhance my understanding of the subject. I regret taking this course.",
    "The professor was not only ineffective but also unprofessional in their interactions with students. Their lectures were a waste of time, and they often seemed to be unprepared. The course content was poorly organized, with assignments that were irrelevant and unhelpful. This was one of the worst courses I have ever taken.",
    "The professor's teaching style was incredibly boring and uninspired. They often seemed to be reading from a script and rarely engaged with the students. The course content was equally terrible, with outdated materials and assignments that did not contribute to my learning. I would not recommend this course to anyone.",
    "The professor was not only unhelpful but also dismissive of students' concerns. Their lectures were poorly organized and difficult to follow. The course content was a mess, with outdated materials and assignments that seemed to have no real purpose. This was a terrible learning experience.",
    "The professor's lack of preparation was evident in every lecture. They often seemed to be making things up as they went along. The course content was equally bad, with outdated materials and assignments that were either too easy or completely irrelevant. This course was a waste of time and money.",
    "The professor's lectures were incredibly boring and lacked any real substance. They often went off on tangents and failed to cover the necessary material. The course content was equally bad, with outdated readings and assignments that did not enhance my understanding of the subject. I regret taking this course.",
    "The professor was one of the worst I have ever encountered. Their lectures were monotonous and unhelpful, and they rarely engaged with the students. The course content was equally disappointing, with poorly organized materials and assignments that did not contribute to my understanding of the subject. I would not recommend this course to anyone.",
    "The professor was consistently late to class and seemed to have no interest in teaching. Their lectures were disjointed and confusing, making it difficult to follow along. The course content was a joke, with outdated materials and assignments that seemed to have no real purpose. This was a terrible learning experience.",
    "The professor's lectures were poorly delivered and lacked any real substance. They often went off on tangents and failed to cover the necessary material. The course content was equally bad, with outdated readings and assignments that did not enhance my understanding of the subject. I regret taking this course.",
    "The professor was not only ineffective but also unprofessional in their interactions with students. Their lectures were a waste of time, and they often seemed to be unprepared. The course content was poorly organized, with assignments that were irrelevant and unhelpful. This was one of the worst courses I have ever taken.",
    "The professor's teaching style was incredibly boring and uninspired. They often seemed to be reading from a script and rarely engaged with the students. The course content was equally terrible, with outdated materials and assignments that did not contribute to my learning. I would not recommend this course to anyone.",
    "The professor was not only unhelpful but also dismissive of students' concerns. Their lectures were poorly organized and difficult to follow. The course content was a mess, with outdated materials and assignments that seemed to have no real purpose. This was a terrible learning experience.",
    "The professor's lack of preparation was evident in every lecture. They often seemed to be making things up as they went along. The course content was equally bad, with outdated materials and assignments that were either too easy or completely irrelevant. This course was a waste of time and money.",
    "The professor's lectures were incredibly boring and lacked any real substance. They often went off on tangents and failed to cover the necessary material. The course content was equally bad, with outdated readings and assignments that did not enhance my understanding of the subject. I regret taking this course.",
    "The professor was one of the worst I have ever encountered. Their lectures were monotonous and unhelpful, and they rarely engaged with the students. The course content was equally disappointing, with poorly organized materials and assignments that did not contribute to my understanding of the subject. I would not recommend this course to anyone.",
    "The professor was consistently late to class and seemed to have no interest in teaching. Their lectures were disjointed and confusing, making it difficult to follow along. The course content was a joke, with outdated materials and assignments that seemed to have no real purpose. This was a terrible learning experience.",
    "The professor's lectures were poorly delivered and lacked any real substance. They often went off on tangents and failed to cover the necessary material. The course content was equally bad, with outdated readings and assignments that did not enhance my understanding of the subject. I regret taking this course.",
    "The professor was not only ineffective but also unprofessional in their interactions with students. Their lectures were a waste of time, and they often seemed to be unprepared. The course content was poorly organized, with assignments that were irrelevant and unhelpful. This was one of the worst courses I have ever taken.",
    "The professor's teaching style was incredibly boring and uninspired. They often seemed to be reading from a script and rarely engaged with the students. The course content was equally terrible, with outdated materials and assignments that did not contribute to my learning. I would not recommend this course to anyone.",
    "The professor was not only unhelpful but also dismissive of students' concerns. Their lectures were poorly organized and difficult to follow. The course content was a mess, with outdated materials and assignments that seemed to have no real purpose. This was a terrible learning experience.",
    "The professor's lack of preparation was evident in every lecture. They often seemed to be making things up as they went along. The course content was equally bad, with outdated materials and assignments that were either too easy or completely irrelevant. This course was a waste of time and money."
]

# Load the existing CSV file
file_path = './combined_course_reviews.csv'
df_existing = pd.read_csv(file_path)

# Create a DataFrame for the new comments
df_new_comments = pd.DataFrame(new_comments, columns=['Review'])

# Append the new comments to the existing DataFrame
df_combined = pd.concat([df_existing, df_new_comments], ignore_index=True)

# Save the updated DataFrame back to a CSV file
output_file_path = './combined_course_reviews.csv'
df_combined.to_csv(output_file_path, index=False)

print(f"Updated file saved to {output_file_path}")
